language: go

go:
  - 1.4

git:
  depth: 1

install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - golint .
  - go test -race ./...
  - go test -cover ./...
